baseURL : "http://example.org/"
languageCode : "ca-es"
title : "RESTAURANT eFe"
theme: "basic-hugo"
menu:
  main:
  - name: Carta
    url: /about
    weight: -110
  - name: Projectes
    url: /projectes/
    weight: -100
