baseURL : "http://example.org/"
languageCode : "ca-es"
title : "RESTAURANT eFe"
theme: "basic-hugo"
menu:
  main:
  - name: Introduccio
    url: /about
    weight: -100
  - name: Carta
    url: /projectes/projecte1/
    weight: -110
  - name: Menu
    url: /projectes/projecte2/
    weight: -110
